spring:
  mvc:
    problemdetails:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/db-lms
    username: postgres
    password: Psql@1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

servlet:
  multipart:
    enabled: true
    max-file-size: 5MB
    max-request-size: 10MB

server:
  port: 0
  forward-headers-strategy: framework

app:
  storage:
    path: ${user.home}/.ijse/lms/users

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

